### ISSUE TITLE
出品時に画像を登録するにはどうしたらいいですか？

### ISSUE THREAD

**Issue by chiemi627** [enpitut2017/a2#76]
## 状況
* 出品しようとした

## 不明点
* 出品物の画像をアップロードしようとしたのですが、項目に「画像パス」と書いてあり、画像をアップロードする方法がわかりませんでした。

## 環境
* PC(Macbook Pro）
* ブラウザ：Chrome

**Comment by omiya-pan** [comment]
すみません、今気づきました。
現在はアップロードできます。
当時は画像のアップロードができなかったため、画像のファイルパスを直接データベースに格納していました。

**Comment by NaOboe** [comment]
解決しました
